### ISSUE TITLE
cannot log in https://cedar.metadatacenter.org/

### ISSUE THREAD

**Issue by froggypaule** [metadatacenter/fairware-workbench-ui#1]
Dear all,
Yes I know this is probably not the place to log this; but I simply couldn't find anywhere to contact you.

The problem: I just created an account, all went well, I confirmed my email, and then.... trying to log in https://cedar.metadatacenter.org/, I am simply faced with a blank screen...

Ta!

**Comment by marcosmro** [comment]
Hi @froggypaule,

All CEDAR systems are live and working as expected. The cause of the blank screen might have been a momentary network issue or a problem with the browser that you are using. Please, try again. If the problem still persists, try the following:
1) If you were not using Chrome, please try Chrome. We test CEDAR on Chrome and Firefox, almost always on Macs, and we've never had any issue with Firefox until recently (https://github.com/metadatacenter/cedar-project/issues/1150). 
2) If you are already using Chrome, please clear the browser cache and try again. (go to Chrome > Clear browsing data).

Please let me know if any of these solutions has worked for you. 

Feel free to enter new issues at https://github.com/metadatacenter/cedar-project.

**Comment by froggypaule** [comment]
Thanks @marcosmro 
Indeed it is the same problem as previously reported. I posted it in  cedar-project#1150.

**Comment by marcosmro** [comment]
Thank you!
